### ISSUE TITLE
Incorrect TXT record applied

### ISSUE THREAD

**Issue by ZMarkC** [helgeerbe/certbot-dns-ionos#8]
'''Certbot failed to authenticate some domains (authenticator: dns-ionos). The Certificate Authority reported these problems:
  Domain: mcraxford.co.uk
  Type:   unauthorized
  Detail: Incorrect TXT record "TobtsFGFOofvrNbtieBI--PrnouL2d1semtJL5nT62Q" found at _acme-challenge.mcraxford.co.uk

Hint: The Certificate Authority failed to verify the DNS TXT records created by --dns-ionos. Ensure the above domains are hosted by this DNS provider, or try increasing --dns-ionos-propagation-seconds (currently 900 seconds).
'''

The incorrect record was created by the plugin. This invalid record is also deleted by the plugin after challenge failure.

Is the TXT record being mangled by the IONOS plugin during transmission?

Let me know what logs or details you would like.
I have reproduced this 3 times.

**Comment by ZMarkC** [comment]
So the I have a wildcats CNAME on my domain.
Once the CNAME was deleted, the challenge was passed. I guess this is not a bug.

**Comment by helgeerbe** [comment]
Hi @ZMarkC , I wasn't aware that ionos is doing business in the UK.  It's been a while I wrote this little piece of code. If I remember right, you can use a CNAME record to delegate the dns-01 challenge to an other dns resolver. That might be the reason here. Did you set the CNAME record? Just deleting it could cause problems. You should check that all your servers could be accessed by name.
